services:
  web_marshell:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - GA4_PROPERTY_ID=${GA4_PROPERTY_ID}
    env_file:
      - .env
    networks:
      - tiktok_net

  api_marshell:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install -g json-server && json-server --watch db.json --port 3007 --host 0.0.0.0"
    networks:
      - tiktok_net

networks:
  tiktok_net:
    name: tiktok_shared_network
    driver: bridge
